# Generated by Django 2.1 on 2018-08-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brief',
            field=models.CharField(default=0, max_length=100, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='goods',
            name='intorduce',
            field=models.CharField(default=1, max_length=100, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.IntegerField(default=5, max_length=5, verbose_name='单位'),
        ),
    ]
