# Generated by Django 2.1 on 2018-08-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180822_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.SmallIntegerField(choices=[(0, '未付款'), (1, '付款中'), (2, '已付款')], default=0, verbose_name='支付状态')),
                ('shipping_status', models.SmallIntegerField(choices=[(0, '未发货'), (1, '已发货'), (2, '已收货'), (3, '退货 ')], default=0, verbose_name='配送状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressee', models.CharField(max_length=30, verbose_name='收件人')),
                ('amply', models.CharField(max_length=100, verbose_name='详细地址')),
                ('zip', models.IntegerField(verbose_name='邮编')),
                ('phone', models.IntegerField(verbose_name='手机')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'verbose_name': '编辑地址',
                'verbose_name_plural': '编辑地址',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.IntegerField(default=5, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='goods',
            field=models.ManyToManyField(through='shop.OrderGoods', to='shop.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete='商品ID', to='shop.Goods'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.OrderInfo', verbose_name='订单ID'),
        ),
    ]
