# Generated by Django 2.1 on 2018-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180828_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机'),
        ),
    ]
