# Generated by Django 2.1 on 2018-08-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180828_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='', max_length=30, verbose_name='地址'),
        ),
    ]
